name: Release Build

on:
  push:
    tags:
      - 'v*'  # 匹配v开头的tag

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        cache: true
        arch: 'win64_msvc2019_64'
        modules: 'qtcharts qtdatavis3d'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -S ${{github.workspace}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}\build\install

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Release

    - name: install
      run: cmake --install ${{github.workspace}}\build --config Release
    - name: generate installer package
      working-directory: ${{github.workspace}}\build
      run: cpack -C Release -G NSIS
    - name: generate zip package
      working-directory: ${{github.workspace}}\build
      run: cpack -C Release -G ZIP

    - name: Package artifacts
      run: |
        mkdir -p release
        cp ${{github.workspace}}/build/*.exe release/
        cp ${{github.workspace}}/build/*.zip release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.exe
          release/*.zip
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
